// <auto-generated />
using System;
using Experimento.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Experimento.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Experimento.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("PreviousHash")
                        .IsUnique();

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.ChemicalCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CachedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CasNumber")
                        .HasColumnType("text");

                    b.Property<string>("Formula")
                        .HasColumnType("text");

                    b.Property<double>("MolarMass")
                        .HasColumnType("double precision");

                    b.Property<int>("PubChemCid")
                        .HasColumnType("integer");

                    b.Property<string>("Smiles")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("PubChemCid")
                        .IsUnique();

                    b.ToTable("ChemicalCatalog");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.ChemicalRegulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Authority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChemicalCatalogEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Authority");

                    b.HasIndex("ChemicalCatalogEntryId", "Authority")
                        .IsUnique();

                    b.ToTable("ChemicalRegulations");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.ExperimentOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualMetricsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ActualSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResultId")
                        .IsUnique();

                    b.ToTable("ExperimentOutcomes");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.Formulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Formulations");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.FormulationComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CasNumber")
                        .HasColumnType("text");

                    b.Property<string>("ChemicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Formula")
                        .HasColumnType("text");

                    b.Property<double>("MolarMass")
                        .HasColumnType("double precision");

                    b.Property<double>("Proportion")
                        .HasColumnType("double precision");

                    b.Property<int?>("PubChemCid")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Smiles")
                        .HasColumnType("text");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("FormulationComponents");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.FormulationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormulationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormulationId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("FormulationVersions");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("KnowledgeChunks");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<global::Experimento.Domain.Enums.KnowledgeStatus>("Status")
                        .HasConversion<string>()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.ToTable("KnowledgeDocuments");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.ModelRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContextOfUse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModelRegistrations");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "EntityId");

                    b.HasIndex("PublishedAtUtc", "AvailableAtUtc", "LeaseUntilUtc");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.PredictionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.HasIndex("VersionId", "RequestedBy");

                    b.ToTable("PredictionJobs");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.PredictionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModelRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SideRiskLevel")
                        .HasColumnType("integer");

                    b.Property<double>("StabilityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("SuccessProbability")
                        .HasColumnType("double precision");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ToxicityScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("ModelRegistrationId");

                    b.ToTable("PredictionResults");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.PredictionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("PredictionReviews");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.RationaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("RationaleItems");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.SimulationCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<double>("SuccessProbability")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("SimulationCandidates");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.SimulationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.HasIndex("VersionId", "RequestedBy");

                    b.ToTable("SimulationJobs");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.SimulationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BestCandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IterationsExecuted")
                        .HasColumnType("integer");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BestCandidateId")
                        .IsUnique();

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("SimulationResults");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.StabilityPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AssayPercent")
                        .HasColumnType("double precision");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double>("TimeDays")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("StabilityPoints", (string)null);
                });

            modelBuilder.Entity("Experimento.Domain.Entities.StabilityStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("StabilityStudies");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.ChemicalRegulation", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.ChemicalCatalogEntry", "ChemicalCatalogEntry")
                        .WithMany()
                        .HasForeignKey("ChemicalCatalogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChemicalCatalogEntry");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.ExperimentOutcome", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.PredictionResult", "Result")
                        .WithOne("Outcome")
                        .HasForeignKey("Experimento.Domain.Entities.ExperimentOutcome", "ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.Formulation", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.Project", "Project")
                        .WithMany("Formulations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.FormulationComponent", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.FormulationVersion", "Version")
                        .WithMany("Components")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.FormulationVersion", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.Formulation", "Formulation")
                        .WithMany("Versions")
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Experimento.Domain.Entities.FormulationConditions", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("FormulationVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DeliveryTarget")
                                .HasColumnType("text");

                            b1.Property<double?>("PhTarget")
                                .HasColumnType("double precision");

                            b1.Property<double?>("PressureKPa")
                                .HasColumnType("double precision");

                            b1.Property<string>("Solvent")
                                .HasColumnType("text");

                            b1.Property<double>("TemperatureCelsius")
                                .HasColumnType("double precision");

                            b1.HasKey("FormulationVersionId");

                            b1.ToTable("FormulationVersions");

                            b1.WithOwner()
                                .HasForeignKey("FormulationVersionId");
                        });

                    b.Navigation("Conditions")
                        .IsRequired();

                    b.Navigation("Formulation");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.KnowledgeDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.PredictionJob", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.FormulationVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.PredictionResult", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.PredictionJob", "Job")
                        .WithOne("Result")
                        .HasForeignKey("Experimento.Domain.Entities.PredictionResult", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Experimento.Domain.Entities.ModelRegistration", "ModelRegistration")
                        .WithMany()
                        .HasForeignKey("ModelRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("ModelRegistration");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.PredictionReview", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.PredictionResult", "Result")
                        .WithMany("Reviews")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Experimento.Domain.Entities.User", "ReviewerUser")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.RationaleItem", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.PredictionResult", "Result")
                        .WithMany("RationaleItems")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.SimulationCandidate", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.SimulationResult", "Result")
                        .WithMany("Candidates")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.SimulationJob", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.FormulationVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.SimulationResult", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.SimulationCandidate", "BestCandidate")
                        .WithOne()
                        .HasForeignKey("Experimento.Domain.Entities.SimulationResult", "BestCandidateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Experimento.Domain.Entities.SimulationJob", "Job")
                        .WithOne("Result")
                        .HasForeignKey("Experimento.Domain.Entities.SimulationResult", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BestCandidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.StabilityPoint", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.StabilityStudy", "Study")
                        .WithMany("Points")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.StabilityStudy", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.FormulationVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.Formulation", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.FormulationVersion", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.PredictionJob", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.PredictionResult", b =>
                {
                    b.Navigation("Outcome");

                    b.Navigation("RationaleItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.Project", b =>
                {
                    b.Navigation("Formulations");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.SimulationJob", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.SimulationResult", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.StabilityStudy", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
